root - INFO - 2023-05-04 11:35:41.025098 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-05-04 11:35:41.155812 - OMS Backend mainloop started.
root - CRITICAL - CRITICAL ERROR:2023-05-04 11:35:41.733682 - OMSB_ADSINT_2
['Traceback (most recent call last):', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 379, in _make_request', '    httplib_response = conn.getresponse(buffering=True)', "TypeError: getresponse() got an unexpected keyword argument 'buffering'", '', 'During handling of the above exception, another exception occurred:', '', 'Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/ADS_Interface.py", line 52, in get_user_data', "    return json.loads(self.get('get/user_data'))", '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/ADS_Interface.py", line 40, in get', '    response = requests.get(self.url + route, headers=headers)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/requests/api.py", line 70, in get', "    return request('get', url, params=params, **kwargs)", '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/requests/api.py", line 56, in request', '    return session.request(method=method, url=url, **kwargs)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 488, in request', '    resp = self.send(prep, **send_kwargs)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 609, in send', '    r = adapter.send(request, **kwargs)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 413, in send', '    resp = conn.urlopen(', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 597, in urlopen', '    httplib_response = self._make_request(conn, method, url,', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request', '    httplib_response = conn.getresponse()', '  File "/Users/vishaljha/anaconda3/lib/python3.8/http/client.py", line 1332, in getresponse', '    response.begin()', '  File "/Users/vishaljha/anaconda3/lib/python3.8/http/client.py", line 303, in begin', '    version, status, reason = self._read_status()', '  File "/Users/vishaljha/anaconda3/lib/python3.8/http/client.py", line 264, in _read_status', '    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")', '  File "/Users/vishaljha/anaconda3/lib/python3.8/socket.py", line 669, in readinto', '    return self._sock.recv_into(b)', 'KeyboardInterrupt']
root - CRITICAL - CRITICAL ERROR:2023-05-04 12:55:16.670344 - Failed to get configs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/Config.py", line 22, in refresh_config', "    self.ROLLOVER_TIME = config_data['ROLLOVER_TIME']", "KeyError: 'ROLLOVER_TIME'"]
root - INFO - 2023-05-04 12:56:10.420662 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-05-04 12:56:10.554181 - OMS Backend mainloop started.
root - INFO - 2023-05-04 12:56:11.305011 - User data obtained.
root - INFO - 2023-05-04 12:56:12.051762 - Spreads obtained.
root - INFO - 2023-05-04 12:56:12.186666 - Config file obtained.
root - INFO - 2023-05-04 12:56:12.312961 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-05-04 12:56:19.393846 - OMSB: Login succesful for backend kite ticker.
root - INFO - 2023-05-04 12:56:19.522766 - Initialising LTP gather thread.
root - INFO - 2023-05-04 12:56:20.054126 - OMSB: Zerodha login for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-05-04 12:56:27.563722 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-05-04 12:56:27.695184 - Order handler initialised.
root - INFO - 2023-05-04 12:56:27.825394 - Creating order handler sub threads.
root - INFO - 2023-05-04 12:56:27.825633 - Starting order handler sub threads.
root - INFO - 2023-05-04 12:56:28.329134 - Placed Zerodha Kite options order for:fin_user_1, instrument:NIFTY23MAY18000PE, qty:50, transaction type:BUY, placed price:99.4, id:231.
root - CRITICAL - CRITICAL ERROR:2023-05-04 12:56:28.472839 - Failed to update order placement in DB. User: fin_user_1. Tradingsymbol:NIFTY23MAY18000PE. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderPlacement.py", line 121, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price, spread_list=spread_list, brokerage_name=user_type, brokerage_id=order_id, debug=debug) # If this fails, infinite order placement -> stop this thread + critical user message', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 572, in update_order_placement', '    update_orderbuffer(username=username,tradingsymbol=tradingsymbol,placed_qty=placed_qty,placed_price=placed_price,conn=db_connection,cur=cur, spread_list= spread_list, debug=debug, brokerage_name=brokerage_name, brokerage_id=brokerage_id)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 439, in update_orderbuffer', '    cur.execute("""', 'sqlite3.OperationalError: no such column: ob.lot_size']
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-05-04 12:58:54.035959 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-05-04 12:58:54.168752 - OMS Backend mainloop started.
root - INFO - 2023-05-04 12:58:54.916247 - User data obtained.
root - INFO - 2023-05-04 12:58:55.671377 - Spreads obtained.
root - INFO - 2023-05-04 12:58:55.797717 - Config file obtained.
root - INFO - 2023-05-04 12:58:55.933097 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-05-04 12:59:03.148527 - OMSB: Login succesful for backend kite ticker.
root - INFO - 2023-05-04 12:59:03.277773 - Initialising LTP gather thread.
root - INFO - 2023-05-04 12:59:03.808971 - OMSB: Zerodha login for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-05-04 12:59:11.308050 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-05-04 12:59:11.439495 - Order handler initialised.
root - INFO - 2023-05-04 12:59:11.570574 - Creating order handler sub threads.
root - INFO - 2023-05-04 12:59:11.570813 - Starting order handler sub threads.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-05-04 13:00:16.421695 - Placed Zerodha Kite options order for:fin_user_1, instrument:NIFTY23MAY18400PE, qty:50, transaction type:BUY, placed price:271.55, id:21.
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:00:16.556013 - Failed to update order placement in DB. User: fin_user_1. Tradingsymbol:NIFTY23MAY18400PE. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderPlacement.py", line 121, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price, spread_list=spread_list, brokerage_name=user_type, brokerage_id=order_id, debug=debug) # If this fails, infinite order placement -> stop this thread + critical user message', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 572, in update_order_placement', '    update_orderbuffer(username=username,tradingsymbol=tradingsymbol,placed_qty=placed_qty,placed_price=placed_price,conn=db_connection,cur=cur, spread_list= spread_list, debug=debug, brokerage_name=brokerage_name, brokerage_id=brokerage_id)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 439, in update_orderbuffer', '    cur.execute("""', 'sqlite3.OperationalError: no such column: ob.lot_size']
root - INFO - 2023-05-04 13:04:26.439864 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-05-04 13:04:26.580883 - OMS Backend mainloop started.
root - INFO - 2023-05-04 13:04:27.334856 - User data obtained.
root - INFO - 2023-05-04 13:04:28.082567 - Spreads obtained.
root - INFO - 2023-05-04 13:04:28.217375 - Config file obtained.
root - INFO - 2023-05-04 13:04:28.348762 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-05-04 13:04:36.236659 - OMSB: Login succesful for backend kite ticker.
root - INFO - 2023-05-04 13:04:36.367374 - Initialising LTP gather thread.
root - INFO - 2023-05-04 13:04:36.922323 - OMSB: Zerodha login for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-05-04 13:04:44.172309 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-05-04 13:04:44.333853 - Order handler initialised.
root - INFO - 2023-05-04 13:04:44.461096 - Creating order handler sub threads.
root - INFO - 2023-05-04 13:04:44.461328 - Starting order handler sub threads.
root - INFO - 2023-05-04 13:04:44.965819 - Placed Zerodha Kite options order for:fin_user_1, instrument:NIFTY23MAY18400PE, qty:50, transaction type:BUY, placed price:261.0, id:393.
root - INFO - 2023-05-04 13:04:45.107320 - 644.881010055542
root - INFO - 2023-05-04 13:04:45.746823 - Placed Zerodha Kite options order for:fin_user_1, instrument:NIFTY23MAY18300PE, qty:-50, transaction type:SELL, placed price:205.95, id:729.
root - INFO - 2023-05-04 13:04:45.903801 - 662.2858047485352
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-05-04 13:05:53.931318 - Placed Zerodha Kite options order for:fin_user_1, instrument:NIFTY23MAY18400PE, qty:-50, transaction type:SELL, placed price:255.0, id:5.
root - INFO - 2023-05-04 13:05:54.078980 - 1655.8668613433838
root - INFO - 2023-05-04 13:05:54.730130 - Placed Zerodha Kite options order for:fin_user_1, instrument:NIFTY23MAY18300PE, qty:50, transaction type:BUY, placed price:201.35, id:90.
root - INFO - 2023-05-04 13:05:54.880372 - 657.8099727630615
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:08.011093 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:08.086583 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:08.200613 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:08.434654 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:08.744900 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:08.884939 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:09.107462 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:09.215759 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:09.290169 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:10.349505 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:11.477596 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:12.623149 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:12.727387 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:13.483985 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:13.759693 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:13.945724 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:14.609555 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:14.899215 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:15.141755 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:15.791926 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:16.036036 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:16.532370 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:17.131879 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:17.173369 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:17.611799 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:18.186921 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:18.338247 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:18.820512 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:19.444595 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 106, in update_ltp', "    DBManager.update_LTP_peg('BANKNIFTY',last_price)", '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 168, in update_LTP_peg', "    cur.execute('UPDATE orderbook SET net_position_value = {} - net_entry_price WHERE index_peg = {} and position = {} and order_status = {};'.format(ltp,gSF(peg),gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: orderbook']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:19.477467 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:20.176462 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:20.644857 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:20.681820 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:21.168954 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:21.734547 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:21.802969 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:22.589588 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:22.945653 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:23.040503 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:23.627052 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:24.085325 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:24.143568 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:24.812890 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:25.225696 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:25.307862 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:25.934246 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:26.356887 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:26.578888 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:27.190139 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:27.635088 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:27.808062 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:28.295910 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:28.772832 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:29.239920 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:29.582506 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 104, in update_ltp', "    DBManager.update_LTP_peg('NIFTY',last_price)", '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 168, in update_LTP_peg', "    cur.execute('UPDATE orderbook SET net_position_value = {} - net_entry_price WHERE index_peg = {} and position = {} and order_status = {};'.format(ltp,gSF(peg),gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: orderbook']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:29.904554 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:30.166490 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:30.939366 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:31.043468 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:31.577135 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:31.938463 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:32.175856 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:32.514845 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:33.182520 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:33.326893 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:33.733460 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:34.390025 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:34.459433 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:35.108689 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:35.593210 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:35.718642 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:36.125871 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:36.741565 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:36.869294 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:37.466669 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:37.889793 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:37.929865 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:38.497465 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:39.025926 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:39.135423 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 104, in update_ltp', "    DBManager.update_LTP_peg('NIFTY',last_price)", '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 168, in update_LTP_peg', "    cur.execute('UPDATE orderbook SET net_position_value = {} - net_entry_price WHERE index_peg = {} and position = {} and order_status = {};'.format(ltp,gSF(peg),gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: orderbook']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:39.751262 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:40.162739 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:40.365167 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:41.133045 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:41.292728 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:41.527355 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:42.218469 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:42.437823 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:42.866391 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:43.395144 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:43.575850 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:44.061162 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:44.707716 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:44.862414 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:45.364943 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 106, in update_ltp', "    DBManager.update_LTP_peg('BANKNIFTY',last_price)", '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 168, in update_LTP_peg', "    cur.execute('UPDATE orderbook SET net_position_value = {} - net_entry_price WHERE index_peg = {} and position = {} and order_status = {};'.format(ltp,gSF(peg),gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: orderbook']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:45.897914 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:45.913098 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:46.399609 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 106, in update_ltp', "    DBManager.update_LTP_peg('BANKNIFTY',last_price)", '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 168, in update_LTP_peg', "    cur.execute('UPDATE orderbook SET net_position_value = {} - net_entry_price WHERE index_peg = {} and position = {} and order_status = {};'.format(ltp,gSF(peg),gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: orderbook']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:47.088136 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:47.280843 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:47.685940 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 106, in update_ltp', "    DBManager.update_LTP_peg('BANKNIFTY',last_price)", '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 168, in update_LTP_peg', "    cur.execute('UPDATE orderbook SET net_position_value = {} - net_entry_price WHERE index_peg = {} and position = {} and order_status = {};'.format(ltp,gSF(peg),gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: orderbook']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:48.361209 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:48.513814 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:48.825082 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:49.660908 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:49.745221 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:50.015450 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:50.653680 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:50.803961 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:51.153728 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:51.810980 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:51.942136 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:52.317990 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:52.989755 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:53.082613 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:53.607581 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:54.170198 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:54.219609 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:54.807129 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:55.373418 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:55.477600 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:55.978781 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:56.514380 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:56.620939 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:57.121124 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:57.656298 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:57.798404 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:58.410270 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:58.803539 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:58.904521 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:59.643415 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:09:59.943384 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:00.249829 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:01.023301 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:01.077838 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:01.306349 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:02.140171 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:02.222591 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:02.616394 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:03.194699 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 104, in update_ltp', "    DBManager.update_LTP_peg('NIFTY',last_price)", '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 168, in update_LTP_peg', "    cur.execute('UPDATE orderbook SET net_position_value = {} - net_entry_price WHERE index_peg = {} and position = {} and order_status = {};'.format(ltp,gSF(peg),gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: orderbook']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:03.361298 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:03.795069 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:04.482845 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:04.507171 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:04.921242 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:05.658534 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:05.689329 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:06.230016 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:06.769002 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:06.861483 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:07.523556 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:08.039225 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:08.076665 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:08.615526 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:09.166970 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:09.230207 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:09.725301 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:10.376849 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:10.460135 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:11.033496 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:11.533395 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:11.620435 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:12.220890 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:12.683832 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:12.796188 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:13.518496 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:13.822494 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:13.962453 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:14.596475 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:14.959363 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:15.113899 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:15.923443 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:16.106750 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:16.540436 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:17.156562 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:17.248123 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 59, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/OrderHandler.py", line 70, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 278, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:17.665266 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
root - CRITICAL - CRITICAL ERROR:2023-05-04 13:10:18.291925 - Failed to update LTPs.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/GatherLTP.py", line 108, in update_ltp', '    DBManager.update_LTP(instrument_token=instrument_token,LTP=last_price)', '  File "/Users/vishaljha/Desktop/FINVANT/Alcubierre_Mk1_OMS/Backend/Scripts/DBManager.py", line 137, in update_LTP', "    cur.execute('UPDATE order_reference SET position_value = {} - position_entry_price WHERE instrument_token = {} and position_type = {} and position_status = {};'.format(LTP,instrument_token,gSF('BUY'),gSF('PLACED')))", 'sqlite3.OperationalError: no such table: order_reference']
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
