root - INFO - 2023-03-31 13:50:22.255491 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-03-31 13:50:22.381787 - OMS Backend mainloop started.
root - INFO - 2023-03-31 13:50:22.543672 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-03-31 13:50:30.994109 - OMSB: Login succesful for backend kite ticker.
root - INFO - 2023-03-31 13:50:31.376986 - OMSB: Zerodha login for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-03-31 13:50:37.953686 - OMSB: Zerodha login succesful for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:30.853125 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:30.981780 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:31.117732 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:31.257807 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:31.399496 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:31.532313 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:31.670262 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:31.811774 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:31.953499 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:32.097952 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:32.230114 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:32.372074 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:32.503215 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:32.632900 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:32.759929 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:32.891101 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:33.025917 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:33.154355 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:33.284657 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:33.422271 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:33.552529 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:33.682930 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:33.813016 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:33.943687 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:34.075217 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:34.207011 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:34.339482 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:34.469875 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:34.597237 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:34.724635 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:34.858004 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:34.991851 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:35.123189 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:35.255676 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:35.382016 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:35.512638 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:35.643236 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:35.776736 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:35.921468 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:36.059509 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:36.195767 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:36.326914 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:36.464761 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:36.602803 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:36.742890 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:36.875658 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:37.015526 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:37.161270 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:37.303638 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:37.445680 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:37.587715 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:37.723654 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:37.864404 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:38.001933 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:38.147174 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:38.286726 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:38.420286 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:38.559626 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:38.706109 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:38.847443 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:38.983196 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:51:39.128642 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    qty_to_place*=(total_qty - placed_qty)/abs(total_qty - placed_qty)', 'ZeroDivisionError: division by zero']
root - INFO - 2023-03-31 13:52:19.447625 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-03-31 13:52:19.575763 - OMS Backend mainloop started.
root - INFO - 2023-03-31 13:52:19.756209 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-03-31 13:52:26.861442 - OMSB: Login succesful for backend kite ticker.
root - INFO - 2023-03-31 13:52:27.246169 - OMSB: Zerodha login for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-03-31 13:52:34.036843 - OMSB: Zerodha login succesful for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-03-31 13:53:23.398285 - Placed Zerodha Kite options order for:TEST, instrument:NIFTY23MAY17400PE, qty:50, transaction type:BUY, placed price:288.0, id:458.
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:53:23.533475 - Failed to update order placement in DB. User: TEST. Tradingsymbol:NIFTY23MAY17400PE. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 132, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price, spread_list=spread_list, brokerage_name=user_type, brokerage_id=order_id, debug=debug) # If this fails, infinite order placement -> stop this thread + critical user message', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/DBManager.py", line 486, in update_order_placement', '    update_orderbuffer(username=username,tradingsymbol=tradingsymbol,placed_qty=placed_qty,placed_price=placed_price,conn=db_connection,cur=cur, spread_list= spread_list, debug=debug, brokerage_name=brokerage_name, brokerage_id=brokerage_id)', "TypeError: update_orderbuffer() got an unexpected keyword argument 'conn'"]
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-03-31 13:54:08.791308 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-03-31 13:54:08.917302 - OMS Backend mainloop started.
root - INFO - 2023-03-31 13:54:09.114434 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-03-31 13:54:15.983700 - OMSB: Login succesful for backend kite ticker.
root - INFO - 2023-03-31 13:54:16.367722 - OMSB: Zerodha login for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-03-31 13:54:22.994839 - OMSB: Zerodha login succesful for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-03-31 13:55:21.011441 - Placed Zerodha Kite options order for:TEST, instrument:NIFTY23MAY17450PE, qty:50, transaction type:BUY, placed price:317.0, id:744.
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:55:21.192040 - Failed to update order placement in DB. User: TEST. Tradingsymbol:NIFTY23MAY17450PE. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 132, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price, spread_list=spread_list, brokerage_name=user_type, brokerage_id=order_id, debug=debug) # If this fails, infinite order placement -> stop this thread + critical user message', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/DBManager.py", line 486, in update_order_placement', '    update_orderbuffer(username=username,tradingsymbol=tradingsymbol,placed_qty=placed_qty,placed_price=placed_price,conn=db_connection,cur=cur, spread_list= spread_list, debug=debug, brokerage_name=brokerage_name, brokerage_id=brokerage_id)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/DBManager.py", line 396, in update_orderbuffer', '    update_order_reference(username=username, position_list=positions_list, placed_price=new_placement_price,order_completion=order_completion,conn=conn,cur=cur, spread_list=spread_list, rollover = rollover, debug=debug, brokerage_name = brokerage_name, brokerage_id = brokerage_id)', "TypeError: update_order_reference() got an unexpected keyword argument 'conn'"]
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-03-31 13:56:28.240037 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-03-31 13:56:28.363091 - OMS Backend mainloop started.
root - INFO - 2023-03-31 13:56:28.535247 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-03-31 13:56:36.296759 - OMSB: Login succesful for backend kite ticker.
root - INFO - 2023-03-31 13:56:36.677608 - OMSB: Zerodha login for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-03-31 13:56:43.457273 - OMSB: Zerodha login succesful for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:56:59.698306 - Failed to refresh lookup table.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/GatherLTP.py", line 64, in refresh_lookup_table', '    self.lookup_table = json.load(f)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/__init__.py", line 293, in load', '    return loads(fp.read(),', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads', '    return _default_decoder.decode(s)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode', '    obj, end = self.raw_decode(s, idx=_w(s, 0).end())', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode', '    raise JSONDecodeError("Expecting value", s, err.value) from None', 'json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)']
root - INFO - 2023-03-31 13:57:00.327503 - Placed Zerodha Kite options order for:TEST, instrument:NIFTY23MAY17450PE, qty:50, transaction type:BUY, placed price:317.0, id:283.
root - CRITICAL - CRITICAL ERROR:2023-03-31 13:57:00.468887 - Failed to update order placement in DB. User: TEST. Tradingsymbol:NIFTY23MAY17450PE. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 132, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price, spread_list=spread_list, brokerage_name=user_type, brokerage_id=order_id, debug=debug) # If this fails, infinite order placement -> stop this thread + critical user message', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/DBManager.py", line 486, in update_order_placement', '    update_orderbuffer(username=username,tradingsymbol=tradingsymbol,placed_qty=placed_qty,placed_price=placed_price,conn=db_connection,cur=cur, spread_list= spread_list, debug=debug, brokerage_name=brokerage_name, brokerage_id=brokerage_id)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/DBManager.py", line 396, in update_orderbuffer', '    update_order_reference(username=username, position_list=positions_list, placed_price=new_placement_price,order_completion=order_completion,conn=conn,cur=cur, spread_list=spread_list, rollover = rollover, debug=debug, brokerage_name = brokerage_name, brokerage_id = brokerage_id)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/DBManager.py", line 473, in update_order_reference', '    addToOrderHistory(cur,order_id, brokerage_name,brokerage_id,username, strategy, tradingsymbol, position_type, instrument_nomenclature, entry_price, quantity, lot_size, time.time())', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/DBManager.py", line 14, in addToOrderHistory', '    cur.execute("INSERT INTO order_history (order_id, brokerage,brokerage_id,  username, strategy_name, tradingsymbol, position, instrument_nomenclature, order_status, order_price, order_qty, order_time) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",(order_id,brokerage_id, user_type ,username, strategy_name, tradingsymbol, position, instrument_nomenclature, \'COMPLETE\', order_price, order_qty*lot_size, order_time))', 'sqlite3.OperationalError: table order_history has no column named brokerage_id']
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-03-31 17:37:17.556572 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-03-31 17:37:17.687463 - OMS Backend mainloop started.
root - INFO - 2023-03-31 17:37:17.862928 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-03-31 17:37:26.927680 - OMSB: Login succesful for backend kite ticker.
root - INFO - 2023-03-31 17:37:27.341558 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-03-31 17:37:34.040999 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-03-31 17:37:58.305497 - Placed Zerodha Kite options order for:TEST, instrument:NIFTY23MAY17400PE, qty:50, transaction type:BUY, placed price:284.05, id:5.
root - INFO - 2023-03-31 17:37:58.442437 - 638.7882232666016
root - INFO - 2023-03-31 17:37:59.356533 - Placed Zerodha Kite options order for:TEST, instrument:NIFTY23MAY17350PE, qty:-50, transaction type:SELL, placed price:264.0, id:825.
root - INFO - 2023-03-31 17:37:59.493117 - 641.3681507110596
root - INFO - 2023-03-31 17:39:07.662543 - Placed Zerodha Kite options order for:TEST, instrument:NIFTY23MAY17500PE, qty:50, transaction type:BUY, placed price:325.2, id:158.
root - INFO - 2023-03-31 17:39:07.790829 - 633.5799694061279
root - INFO - 2023-03-31 17:39:08.706284 - Placed Zerodha Kite options order for:TEST, instrument:NIFTY23MAY17450PE, qty:-50, transaction type:SELL, placed price:309.2, id:681.
root - INFO - 2023-03-31 17:39:08.845404 - 642.146110534668
root - INFO - 2023-03-31 17:39:51.485403 - Placed Zerodha Kite options order for:TEST, instrument:NIFTY23MAY17500PE, qty:50, transaction type:BUY, placed price:325.2, id:590.
root - INFO - 2023-03-31 17:39:51.624265 - 642.6708698272705
root - INFO - 2023-03-31 17:39:52.537548 - Placed Zerodha Kite options order for:TEST, instrument:NIFTY23MAY17450PE, qty:-50, transaction type:SELL, placed price:309.2, id:813.
root - INFO - 2023-03-31 17:39:52.666885 - 632.4429512023926
root - CRITICAL - CRITICAL ERROR:2023-03-31 17:42:50.622745 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 53, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 67, in place_pending_orders', '    pending_orders = DBManager.get_pending_orders(username)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/DBManager.py", line 260, in get_pending_orders', "    cur.execute('SELECT tradingsymbol, exchange_token, lot_size, total_qty, placed_qty, last_order_placement, exchange, segment, instrument_token from orderbuffer WHERE username = {} and (total_qty!=placed_qty or total_qty == 0);'.format(gSF(username)))", 'sqlite3.OperationalError: no such table: orderbuffer']
root - INFO - 2023-03-31 17:43:34.409102 - Placed Zerodha Kite futures order for:TEST, instrument:NIFTY23MAYFUT, qty:50, transaction type:BUY, placed price:17499.0, id:994.
root - INFO - 2023-03-31 17:43:34.590884 - 182.69705772399902
