root - INFO - 2023-01-30 13:29:02.978644 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-01-30 13:29:03.664492 - OMS Backend mainloop started.
root - INFO - 2023-01-30 13:29:04.275428 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-01-30 13:29:12.001588 - OMSB: Login succesful for backend kite ticker.
root - INFO - 2023-01-30 13:29:12.819395 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:29:12.819737 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:29:12.819980 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:29:12.820190 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:29:20.534566 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:29:20.839312 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:29:20.973569 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:29:21.082860 - OMSB: Zerodha login for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-01-30 13:29:21.653585 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:29:21.663431 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:29:22.383804 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:29:23.396535 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:29:29.498438 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:29:30.058855 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:29:30.866281 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:29:31.303322 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:29:31.467277 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:29:31.513946 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:29:32.112686 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:29:33.035588 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:29:37.380675 - OMSB: Zerodha login succesful for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-01-30 13:29:37.838897 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:29:40.112089 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:29:40.707073 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:29:40.818558 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:29:40.892908 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:29:41.667496 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:29:42.229215 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:29:45.648319 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:29:46.211841 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:29:48.578000 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:29:49.187606 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:29:49.968605 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:29:50.174532 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:29:50.551049 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:29:51.201726 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:29:53.398442 - OMSB: Zerodha login succesful for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-01-30 13:29:57.100029 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:29:58.935060 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:29:59.343549 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:30:13.896452 - Placed Zerodha Kite futures order for:gBlsvbrm, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:252.
root - INFO - 2023-01-30 13:30:13.899433 - Placed Zerodha Kite futures order for:SxzOECVf, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:524.
root - INFO - 2023-01-30 13:30:13.902431 - Placed Zerodha Kite futures order for:fOZREsDu, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:486.
root - INFO - 2023-01-30 13:30:13.906150 - Placed Zerodha Kite futures order for:kQbpwQYb, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:544.
root - INFO - 2023-01-30 13:30:13.906532 - Placed Zerodha Kite futures order for:EkOEKXrF, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:625.
root - INFO - 2023-01-30 13:30:13.907017 - Placed Zerodha Kite futures order for:jjlUIWLB, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:281.
root - INFO - 2023-01-30 13:30:13.908552 - Placed Zerodha Kite futures order for:pOsRxVPE, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:525.
root - INFO - 2023-01-30 13:30:13.912120 - Placed Zerodha Kite futures order for:WvmqxXhi, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:764.
root - INFO - 2023-01-30 13:30:13.916424 - Placed Zerodha Kite futures order for:XWoSfnXV, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:605.
root - INFO - 2023-01-30 13:30:13.917104 - Placed Zerodha Kite futures order for:ylHYoNcf, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:676.
root - INFO - 2023-01-30 13:30:13.917180 - Placed Zerodha Kite futures order for:nmykayHe, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:442.
root - INFO - 2023-01-30 13:30:13.919803 - Placed Zerodha Kite futures order for:GZCxuGYX, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:996.
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:14.102583 - Failed to update order placement in DB. User: jjlUIWLB. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:14.225207 - Failed to update order placement in DB. User: gBlsvbrm. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:14.334623 - Failed to update order placement in DB. User: fOZREsDu. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:14.423943 - Failed to update order placement in DB. User: pOsRxVPE. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:14.497917 - Failed to update order placement in DB. User: WvmqxXhi. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:14.584203 - Failed to update order placement in DB. User: kQbpwQYb. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:14.707463 - Failed to update order placement in DB. User: EkOEKXrF. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:14.796681 - Failed to update order placement in DB. User: GZCxuGYX. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:14.891661 - Failed to update order placement in DB. User: SxzOECVf. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:14.985970 - Failed to update order placement in DB. User: XWoSfnXV. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:15.106407 - Failed to update order placement in DB. User: ylHYoNcf. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:15.218166 - Failed to update order placement in DB. User: nmykayHe. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:15.318123 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:15.401249 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:15.514152 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:15.617861 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:15.698142 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:15.792928 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:15.881705 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:15.973806 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:16.075458 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:16.158908 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:16.255561 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:16.334277 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - INFO - 2023-01-30 13:30:16.457094 - Placed Zerodha Kite futures order for:jjlUIWLB, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:445.
root - INFO - 2023-01-30 13:30:16.558388 - Placed Zerodha Kite futures order for:gBlsvbrm, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:532.
root - INFO - 2023-01-30 13:30:16.664688 - Placed Zerodha Kite futures order for:fOZREsDu, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:343.
root - INFO - 2023-01-30 13:30:16.771950 - Placed Zerodha Kite futures order for:pOsRxVPE, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:500.
root - INFO - 2023-01-30 13:30:16.893266 - Placed Zerodha Kite futures order for:WvmqxXhi, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:588.
root - INFO - 2023-01-30 13:30:16.977862 - Placed Zerodha Kite futures order for:kQbpwQYb, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:23.
root - INFO - 2023-01-30 13:30:17.069568 - Placed Zerodha Kite futures order for:EkOEKXrF, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:323.
root - INFO - 2023-01-30 13:30:17.153020 - Placed Zerodha Kite futures order for:GZCxuGYX, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:909.
root - INFO - 2023-01-30 13:30:17.245378 - Placed Zerodha Kite futures order for:SxzOECVf, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:857.
root - INFO - 2023-01-30 13:30:17.357953 - Placed Zerodha Kite futures order for:XWoSfnXV, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:160.
root - INFO - 2023-01-30 13:30:17.485092 - Placed Zerodha Kite futures order for:ylHYoNcf, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:315.
root - INFO - 2023-01-30 13:30:17.578885 - Placed Zerodha Kite futures order for:nmykayHe, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:141.
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:17.667114 - Failed to update order placement in DB. User: jjlUIWLB. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:17.762310 - Failed to update order placement in DB. User: gBlsvbrm. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:17.862600 - Failed to update order placement in DB. User: fOZREsDu. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:17.963352 - Failed to update order placement in DB. User: pOsRxVPE. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:18.041174 - Failed to update order placement in DB. User: WvmqxXhi. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:18.123047 - Failed to update order placement in DB. User: kQbpwQYb. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:18.217732 - Failed to update order placement in DB. User: EkOEKXrF. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:18.338198 - Failed to update order placement in DB. User: GZCxuGYX. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:18.444042 - Failed to update order placement in DB. User: SxzOECVf. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:18.533733 - Failed to update order placement in DB. User: XWoSfnXV. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:18.640167 - Failed to update order placement in DB. User: ylHYoNcf. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:18.739865 - Failed to update order placement in DB. User: nmykayHe. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:18.835929 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:18.926862 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:19.034967 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:19.166102 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:19.248646 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:19.355266 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:19.468021 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:19.572487 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:19.657659 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:19.755910 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:19.862391 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:19.950670 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:20.082432 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 76, in place_pending_orders', '    kill = placeOrder(user_type=user_type,username=username,tradingsymbol=tradingsymbol,exchange_token=exchange_token,instrument_token=instrument_token,lot_size=lot_size,qty=qty_to_place,exchange=exchange, segment= segment,brokerage_object=brokerage_object,spread_list=spread_list,log_interface=self.log_interface, paper_trade=paper_trade)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 16, in placeOrder', '    LTP_Table = json.load(f)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/__init__.py", line 293, in load', '    return loads(fp.read(),', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads', '    return _default_decoder.decode(s)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode', '    obj, end = self.raw_decode(s, idx=_w(s, 0).end())', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode', '    raise JSONDecodeError("Expecting value", s, err.value) from None', 'json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)']
root - INFO - 2023-01-30 13:30:20.163259 - Placed Zerodha Kite futures order for:gBlsvbrm, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:104.
root - INFO - 2023-01-30 13:30:20.260466 - Placed Zerodha Kite futures order for:fOZREsDu, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:805.
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:20.371421 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 76, in place_pending_orders', '    kill = placeOrder(user_type=user_type,username=username,tradingsymbol=tradingsymbol,exchange_token=exchange_token,instrument_token=instrument_token,lot_size=lot_size,qty=qty_to_place,exchange=exchange, segment= segment,brokerage_object=brokerage_object,spread_list=spread_list,log_interface=self.log_interface, paper_trade=paper_trade)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 16, in placeOrder', '    LTP_Table = json.load(f)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/__init__.py", line 293, in load', '    return loads(fp.read(),', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads', '    return _default_decoder.decode(s)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode', '    obj, end = self.raw_decode(s, idx=_w(s, 0).end())', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode', '    raise JSONDecodeError("Expecting value", s, err.value) from None', 'json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)']
root - INFO - 2023-01-30 13:30:20.486773 - Placed Zerodha Kite futures order for:WvmqxXhi, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:653.
root - INFO - 2023-01-30 13:30:20.569659 - Placed Zerodha Kite futures order for:kQbpwQYb, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:763.
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:20.669381 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 76, in place_pending_orders', '    kill = placeOrder(user_type=user_type,username=username,tradingsymbol=tradingsymbol,exchange_token=exchange_token,instrument_token=instrument_token,lot_size=lot_size,qty=qty_to_place,exchange=exchange, segment= segment,brokerage_object=brokerage_object,spread_list=spread_list,log_interface=self.log_interface, paper_trade=paper_trade)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 16, in placeOrder', '    LTP_Table = json.load(f)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/__init__.py", line 293, in load', '    return loads(fp.read(),', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads', '    return _default_decoder.decode(s)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode', '    obj, end = self.raw_decode(s, idx=_w(s, 0).end())', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode', '    raise JSONDecodeError("Expecting value", s, err.value) from None', 'json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)']
root - INFO - 2023-01-30 13:30:20.777528 - Placed Zerodha Kite futures order for:GZCxuGYX, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:434.
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:20.882713 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 76, in place_pending_orders', '    kill = placeOrder(user_type=user_type,username=username,tradingsymbol=tradingsymbol,exchange_token=exchange_token,instrument_token=instrument_token,lot_size=lot_size,qty=qty_to_place,exchange=exchange, segment= segment,brokerage_object=brokerage_object,spread_list=spread_list,log_interface=self.log_interface, paper_trade=paper_trade)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 16, in placeOrder', '    LTP_Table = json.load(f)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/__init__.py", line 293, in load', '    return loads(fp.read(),', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads', '    return _default_decoder.decode(s)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode', '    obj, end = self.raw_decode(s, idx=_w(s, 0).end())', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode', '    raise JSONDecodeError("Expecting value", s, err.value) from None', 'json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:20.998605 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 76, in place_pending_orders', '    kill = placeOrder(user_type=user_type,username=username,tradingsymbol=tradingsymbol,exchange_token=exchange_token,instrument_token=instrument_token,lot_size=lot_size,qty=qty_to_place,exchange=exchange, segment= segment,brokerage_object=brokerage_object,spread_list=spread_list,log_interface=self.log_interface, paper_trade=paper_trade)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 16, in placeOrder', '    LTP_Table = json.load(f)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/__init__.py", line 293, in load', '    return loads(fp.read(),', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads', '    return _default_decoder.decode(s)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode', '    obj, end = self.raw_decode(s, idx=_w(s, 0).end())', '  File "/Users/vishaljha/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode', '    raise JSONDecodeError("Expecting value", s, err.value) from None', 'json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)']
root - INFO - 2023-01-30 13:30:21.117068 - Placed Zerodha Kite futures order for:ylHYoNcf, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:882.
root - INFO - 2023-01-30 13:30:21.200719 - Placed Zerodha Kite futures order for:nmykayHe, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:225.
root - INFO - 2023-01-30 13:30:21.296142 - Placed Zerodha Kite futures order for:jjlUIWLB, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:405.
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:21.380554 - Failed to update order placement in DB. User: gBlsvbrm. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:21.477716 - Failed to update order placement in DB. User: fOZREsDu. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - INFO - 2023-01-30 13:30:21.574482 - Placed Zerodha Kite futures order for:pOsRxVPE, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:678.
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:21.658243 - Failed to update order placement in DB. User: WvmqxXhi. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:21.768216 - Failed to update order placement in DB. User: kQbpwQYb. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - INFO - 2023-01-30 13:30:21.866113 - Placed Zerodha Kite futures order for:EkOEKXrF, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:710.
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:21.964448 - Failed to update order placement in DB. User: GZCxuGYX. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - INFO - 2023-01-30 13:30:22.065752 - Placed Zerodha Kite futures order for:SxzOECVf, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:153.
root - INFO - 2023-01-30 13:30:22.170165 - Placed Zerodha Kite futures order for:XWoSfnXV, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17631.95, id:440.
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:22.245545 - Failed to update order placement in DB. User: ylHYoNcf. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:22.346826 - Failed to update order placement in DB. User: nmykayHe. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:22.523146 - Failed to initialise Log server/ADS.
['Traceback (most recent call last):', '  File "Main.py", line 30, in __init__', '    self.start()', '  File "Main.py", line 38, in start', '    self.main_loop()', '  File "Main.py", line 78, in main_loop', '    sleep(1)', 'KeyboardInterrupt']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:22.473908 - Failed to update order placement in DB. User: jjlUIWLB. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:22.581635 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:22.659341 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:22.762860 - Failed to update order placement in DB. User: pOsRxVPE. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:22.868872 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:30:22.950652 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 46, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 78, in place_pending_orders', '    sys.exit(1)', 'SystemExit: 1']
root - INFO - 2023-01-30 13:42:12.974664 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-01-30 13:42:13.579988 - OMS Backend mainloop started.
root - INFO - 2023-01-30 13:42:14.291972 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-01-30 13:42:22.554115 - OMSB: Login succesful for backend kite ticker.
root - INFO - 2023-01-30 13:42:23.354353 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:42:23.356101 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:42:23.356845 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:42:23.357810 - OMSB: Zerodha login for WG5235.
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:42:31.419878 - OMSB: Failed auto login to kite for user:WG5235.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/AutoLoginZerodha.py", line 119, in auto_login_zerodha', '    data = kite.generate_session(key, api_secret=api_secret)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/kiteconnect/connect.py", line 258, in generate_session', '    resp = self._post("api.token", params={', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/kiteconnect/connect.py", line 841, in _post', '    return self._request(route, "POST", url_args=url_args, params=params, is_json=is_json, query_params=query_params)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/kiteconnect/connect.py", line 913, in _request', '    raise exp(data["message"], code=r.status_code)', 'kiteconnect.exceptions.InputException: `request_token` should be minimum 10 characters in length.']
root - INFO - 2023-01-30 13:42:31.434920 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:42:31.790589 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:42:31.965920 - OMSB: Zerodha login for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-01-30 13:42:32.455402 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:42:32.863190 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:42:32.936984 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:42:34.376607 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:42:40.384336 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:42:40.879756 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:42:40.898064 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:42:41.933372 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:42:42.307648 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:42:42.774067 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:42:43.021284 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:42:43.491686 - OMSB: Zerodha login for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Retrying connection. Retry attempt count: 1. Next retry in around: 2 seconds
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:42:52.687089 - OMSB: Failed auto login to kite for user:WG5235.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/AutoLoginZerodha.py", line 119, in auto_login_zerodha', '    data = kite.generate_session(key, api_secret=api_secret)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/kiteconnect/connect.py", line 255, in generate_session', '    h = hashlib.sha256(self.api_key.encode("utf-8") + request_token.encode("utf-8") + api_secret.encode("utf-8"))', "AttributeError: 'int' object has no attribute 'encode'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:42:53.607249 - OMSB: Failed auto login to kite for user:WG5235.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/AutoLoginZerodha.py", line 119, in auto_login_zerodha', '    data = kite.generate_session(key, api_secret=api_secret)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/kiteconnect/connect.py", line 255, in generate_session', '    h = hashlib.sha256(self.api_key.encode("utf-8") + request_token.encode("utf-8") + api_secret.encode("utf-8"))', "AttributeError: 'int' object has no attribute 'encode'"]
kiteconnect.ticker - ERROR - Retrying connection. Retry attempt count: 2. Next retry in around: 6 seconds
root - INFO - 2023-01-30 13:43:22.327875 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:43:22.964783 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:43:23.022718 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:43:24.209600 - OMSB: Zerodha login for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-01-30 13:43:32.583247 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:43:33.138561 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:43:34.666296 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:43:35.273224 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:43:40.440320 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:43:43.296457 - OMSB: Zerodha login succesful for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:22.280635 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:22.288883 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:22.294730 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:22.363113 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:22.368082 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:22.371493 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:22.370039 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:22.372555 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:22.372956 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:22.373585 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:22.506977 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:22.595252 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:22.696246 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:22.783046 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:22.863980 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:22.960882 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:23.053835 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:23.148937 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:23.223310 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:23.330616 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:23.424393 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:23.526802 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:23.645805 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:23.733366 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:23.817832 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:23.921977 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:24.021006 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:24.127060 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:24.208694 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:24.322840 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:24.417721 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:24.536549 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:24.648288 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:24.745868 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:24.849955 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:24.941149 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:25.033336 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:25.132861 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:25.202400 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:25.289618 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:25.376530 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:25.450345 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:25.550612 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:25.638033 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:25.758069 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:25.876293 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:25.965111 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:26.087405 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:26.203080 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:26.284704 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:26.410455 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:26.511420 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:26.611161 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:26.701588 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:26.822682 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:26.917667 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:27.022417 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:27.131511 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:27.233416 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:27.352323 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:27.457301 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:27.550148 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:27.612951 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:27.713011 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:27.865709 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:27.937877 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:28.036398 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:28.145502 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:28.261069 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:28.373650 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:28.465890 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:28.569530 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:28.668646 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:28.776556 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:28.863307 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:28.979213 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:29.071349 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:29.153435 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:29.255961 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:29.365580 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:29.467061 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:29.575357 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:29.659759 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:29.766047 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:29.851193 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:29.956019 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:30.036710 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:30.143229 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:30.220564 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:30.324339 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:30.428295 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:30.510819 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:30.606084 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:30.708487 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:30.826640 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:30.904843 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:31.018657 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:31.119563 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:31.199784 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:31.329830 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:31.398667 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:31.464810 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:31.556546 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:31.666847 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:31.752856 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:31.856176 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:31.965125 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:32.044105 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:32.139711 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:32.259314 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:32.362597 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:32.466739 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:32.555581 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:32.659759 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:32.744618 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:32.828809 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:32.924024 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:33.022591 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:33.110113 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:33.190443 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:33.283021 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:33.376935 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:33.505624 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:33.626494 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:33.741988 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:33.853384 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:33.953043 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:34.059922 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:34.152286 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:34.259018 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:34.356157 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:34.468158 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:34.553622 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:34.648520 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:34.748194 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:34.865306 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:34.960497 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:35.068488 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:35.136143 - Failed to initialise Log server/ADS.
['Traceback (most recent call last):', '  File "Main.py", line 30, in __init__', '    self.start()', '  File "Main.py", line 38, in start', '    self.main_loop()', '  File "Main.py", line 78, in main_loop', '    sleep(1)', 'KeyboardInterrupt']
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:35.182155 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:35.249801 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:45:35.340160 - Failed to clear pending orders.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 49, in thread_function', '    self.place_pending_orders(username, spread_list= self.spread_list, cntr = thread_no)', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderHandler.py", line 79, in place_pending_orders', '    if self.kill[cntr]:', "TypeError: 'bool' object is not subscriptable"]
root - INFO - 2023-01-30 13:46:52.762751 - Finvant Alcubierre Mk1 OMS Backend turned on.
root - INFO - 2023-01-30 13:46:53.212837 - OMS Backend mainloop started.
root - INFO - 2023-01-30 13:46:53.915525 - OMSB: Logging in for backend kite ticker.
root - INFO - 2023-01-30 13:47:01.125238 - OMSB: Login succesful for backend kite ticker.
root - INFO - 2023-01-30 13:47:01.964555 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:47:01.965150 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:47:01.966294 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:47:01.967484 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:47:10.017127 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:47:10.307665 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:47:10.417892 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:47:10.503455 - OMSB: Zerodha login for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-01-30 13:47:10.957036 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:47:11.459960 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:47:11.629253 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:47:13.488459 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:47:19.653374 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:47:19.803252 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:47:20.045176 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:47:20.229258 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:47:20.782494 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:47:20.812513 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:47:21.335617 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:47:22.619040 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:47:28.642829 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:47:29.317070 - OMSB: Zerodha login for WG5235.
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:47:30.003845 - OMSB: Failed auto login to kite for user:WG5235.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/AutoLoginZerodha.py", line 119, in auto_login_zerodha', '    data = kite.generate_session(key, api_secret=api_secret)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/kiteconnect/connect.py", line 258, in generate_session', '    resp = self._post("api.token", params={', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/kiteconnect/connect.py", line 841, in _post', '    return self._request(route, "POST", url_args=url_args, params=params, is_json=is_json, query_params=query_params)', '  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/kiteconnect/connect.py", line 913, in _request', '    raise exp(data["message"], code=r.status_code)', 'kiteconnect.exceptions.InputException: `request_token` should be minimum 10 characters in length.']
root - INFO - 2023-01-30 13:47:30.021183 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:47:30.303645 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:47:30.580855 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:47:31.091956 - OMSB: Zerodha login for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-01-30 13:47:31.537001 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:47:36.882335 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:47:37.359227 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:47:39.643294 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:47:40.150681 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:47:40.197515 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:47:40.932970 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:47:41.026095 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:47:41.685116 - OMSB: Zerodha login for WG5235.
root - INFO - 2023-01-30 13:47:45.458029 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:47:48.044343 - OMSB: Zerodha login succesful for WG5235.
kiteconnect.ticker - ERROR - Connection error: 1006 - connection was closed uncleanly (None)
kiteconnect.ticker - ERROR - Connection closed: 1006 - connection was closed uncleanly (None)
root - INFO - 2023-01-30 13:47:49.454799 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:47:50.257053 - OMSB: Zerodha login succesful for WG5235.
root - INFO - 2023-01-30 13:47:50.766883 - Placed Zerodha Kite futures order for:nmykayHe, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17567.65, id:243.
root - INFO - 2023-01-30 13:47:50.769378 - Placed Zerodha Kite futures order for:jjlUIWLB, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17567.65, id:12.
root - INFO - 2023-01-30 13:47:50.772209 - Placed Zerodha Kite futures order for:gBlsvbrm, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17567.65, id:260.
root - INFO - 2023-01-30 13:47:50.774748 - Placed Zerodha Kite futures order for:SxzOECVf, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17567.65, id:168.
root - INFO - 2023-01-30 13:47:50.777532 - Placed Zerodha Kite futures order for:ylHYoNcf, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17567.65, id:484.
root - INFO - 2023-01-30 13:47:50.780735 - Placed Zerodha Kite futures order for:EkOEKXrF, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17567.65, id:635.
root - INFO - 2023-01-30 13:47:50.782019 - Placed Zerodha Kite futures order for:WvmqxXhi, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17567.65, id:449.
root - INFO - 2023-01-30 13:47:50.783754 - Placed Zerodha Kite futures order for:GZCxuGYX, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17567.65, id:862.
root - INFO - 2023-01-30 13:47:50.784035 - Placed Zerodha Kite futures order for:fOZREsDu, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17567.65, id:371.
root - INFO - 2023-01-30 13:47:50.785961 - Placed Zerodha Kite futures order for:XWoSfnXV, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17567.65, id:670.
root - INFO - 2023-01-30 13:47:50.788256 - Placed Zerodha Kite futures order for:pOsRxVPE, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17567.65, id:191.
root - INFO - 2023-01-30 13:47:50.791574 - Placed Zerodha Kite futures order for:kQbpwQYb, instrument:NIFTY23FEBFUT, qty:50, transaction type:BUY, placed price:17567.65, id:279.
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:47:51.325068 - Failed to update order placement in DB. User: gBlsvbrm. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:47:52.011320 - Failed to update order placement in DB. User: nmykayHe. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:47:52.470114 - Failed to update order placement in DB. User: EkOEKXrF. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:47:52.980410 - Failed to update order placement in DB. User: ylHYoNcf. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:47:53.576778 - Failed to update order placement in DB. User: jjlUIWLB. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:47:54.093856 - Failed to update order placement in DB. User: SxzOECVf. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:47:54.693898 - Failed to update order placement in DB. User: fOZREsDu. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:47:55.188028 - Failed to update order placement in DB. User: WvmqxXhi. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:47:55.698535 - Failed to update order placement in DB. User: GZCxuGYX. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:47:56.148311 - Failed to update order placement in DB. User: kQbpwQYb. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:47:56.614194 - Failed to update order placement in DB. User: pOsRxVPE. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:47:57.255935 - Failed to update order placement in DB. User: XWoSfnXV. Tradingsymbol:NIFTY23FEBFUT. QTY:50.
['Traceback (most recent call last):', '  File "/Users/vishaljha/Desktop/FINVANT/API/Backend/Scripts/OrderPlacement.py", line 76, in placeOrder', '    update_order_placement(username=username,tradingsymbol=tradingsymbol,placed_qty=qty,placed_price=placed_price) # If this fails, infinite order placement -> stop this thread + critical user message', "TypeError: update_order_placement() missing 1 required positional argument: 'spread_list'"]
root - CRITICAL - CRITICAL ERROR:2023-01-30 13:49:08.621976 - Failed to initialise Log server/ADS.
['Traceback (most recent call last):', '  File "Main.py", line 30, in __init__', '    self.start()', '  File "Main.py", line 38, in start', '    self.main_loop()', '  File "Main.py", line 78, in main_loop', '    sleep(1)', 'KeyboardInterrupt']
