root - INFO - 2023-06-15 00:30:01.908706 - OMS Server turned on.
uvicorn.error - INFO - Started server process [79196]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7f7bc78b7dc0>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [79196]
root - INFO - 2023-06-15 00:33:57.378186 - OMS Server turned on.
uvicorn.error - INFO - Started server process [79453]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7f96b10b6dc0>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
root - INFO - 2023-06-15 00:35:34.827531 - Order placed for fin_user_1 NOVA NIFTY OPEN SHORT -1 0 0
root - INFO - 2023-06-15 00:35:34.999080 - Order placement successful for users: [{'user_name': 'fin_user_1', 'strategy': 'NOVA', 'instrument_nomenclature': 'NIFTY', 'position': 'OPEN SHORT', 'target': 0, 'stoploss': 0, 'quantity': 1}]
root - INFO - 2023-06-15 01:22:29.422186 - Order placed for fin_user_1 NOVA NIFTY CLOSE SHORT -1 0 0
root - INFO - 2023-06-15 01:22:29.647688 - Order placement successful for users: [{'user_name': 'fin_user_1', 'strategy': 'NOVA', 'instrument_nomenclature': 'NIFTY', 'position': 'CLOSE SHORT', 'target': 0, 'stoploss': 0}]
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Finished server process [79453]
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - ERROR - Traceback (most recent call last):
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 624, in lifespan
    await receive()
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/Users/vishaljha/anaconda3/lib/python3.8/asyncio/queues.py", line 163, in get
    await getter
asyncio.exceptions.CancelledError

root - INFO - 2023-06-15 01:31:43.657921 - OMS Server turned on.
uvicorn.error - INFO - Started server process [80494]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7fc4b515bdc0>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
root - INFO - 2023-06-15 01:32:12.685672 - Order placed for fin_user_1 NOVA NIFTY_SYNTHETIC_INTRADAY_LONG BUY 1 0 0
root - INFO - 2023-06-15 01:32:12.845850 - Order placement successful for users: [{'user_name': 'fin_user_1', 'strategy': 'NOVA', 'instrument_nomenclature': 'NIFTY_SYNTHETIC_INTRADAY_LONG', 'position': 'BUY', 'target': 0, 'stoploss': 0, 'quantity': 1}]
uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "./main.py", line 1180, in create_order
    if placeOrder(user_name, strategy, instrument_nomenclature, position, quantity, stoploss, target, nomenclature_to_details):
  File "./main.py", line 497, in placeOrder
    ret = addOrderToOrderReference(order_id = order_id, username=username, instrument_nomenclature = instrument_nomenclature, quantity = quantity, position = position, strategy=strategy_name, nomenclature_to_details=nomenclature_to_details)
  File "./main.py", line 652, in addOrderToOrderReference
    return ret
UnboundLocalError: local variable 'ret' referenced before assignment
root - INFO - 2023-06-15 01:33:09.718948 - Order placement successful for users: []
root - INFO - 2023-06-15 01:33:33.795824 - Order placement successful for users: []
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Finished server process [80494]
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - ERROR - Traceback (most recent call last):
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 624, in lifespan
    await receive()
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/Users/vishaljha/anaconda3/lib/python3.8/asyncio/queues.py", line 163, in get
    await getter
asyncio.exceptions.CancelledError

root - INFO - 2023-06-15 12:15:11.661004 - OMS Server turned on.
uvicorn.error - INFO - Started server process [83576]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7f8c46674dc0>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
root - INFO - 2023-06-15 12:32:20.224774 - Order placed for fin_user_1 NOVA NIFTY_SYNTHETIC_INTRADAY_LONG BUY 1 0 0
root - INFO - 2023-06-15 12:32:20.415452 - Order placement successful for users: [{'user_name': 'fin_user_1', 'strategy': 'NOVA', 'instrument_nomenclature': 'NIFTY_SYNTHETIC_INTRADAY_LONG', 'position': 'BUY', 'target': 0, 'stoploss': 0, 'quantity': 1}]
uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "./main.py", line 1180, in create_order
    if placeOrder(user_name, strategy, instrument_nomenclature, position, quantity, stoploss, target, nomenclature_to_details):
  File "./main.py", line 497, in placeOrder
    ret = addOrderToOrderReference(order_id = order_id, username=username, instrument_nomenclature = instrument_nomenclature, quantity = quantity, position = position, strategy=strategy_name, nomenclature_to_details=nomenclature_to_details)
  File "./main.py", line 652, in addOrderToOrderReference
    return ret
UnboundLocalError: local variable 'ret' referenced before assignment
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [83576]
root - INFO - 2023-06-15 12:33:34.561471 - OMS Server turned on.
uvicorn.error - INFO - Started server process [86675]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7f9cd8087dc0>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "./main.py", line 1180, in create_order
    if placeOrder(user_name, strategy, instrument_nomenclature, position, quantity, stoploss, target, nomenclature_to_details):
  File "./main.py", line 497, in placeOrder
    ret = addOrderToOrderReference(order_id = order_id, username=username, instrument_nomenclature = instrument_nomenclature, quantity = quantity, position = position, strategy=strategy_name, nomenclature_to_details=nomenclature_to_details)
  File "./main.py", line 652, in addOrderToOrderReference
    return ret
UnboundLocalError: local variable 'ret' referenced before assignment
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [86675]
root - INFO - 2023-06-15 12:44:41.134733 - OMS Server turned on.
uvicorn.error - INFO - Started server process [87232]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7fc1c8076dc0>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "./main.py", line 1183, in create_order
    if placeOrder(user_name, strategy, instrument_nomenclature, position, quantity, stoploss, target, nomenclature_to_details):
  File "./main.py", line 497, in placeOrder
    ret = addOrderToOrderReference(order_id = order_id, username=username, instrument_nomenclature = instrument_nomenclature, quantity = quantity, position = position, strategy=strategy_name, nomenclature_to_details=nomenclature_to_details)
  File "./main.py", line 652, in addOrderToOrderReference
    return ret
UnboundLocalError: local variable 'ret' referenced before assignment
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [87232]
root - INFO - 2023-06-15 12:45:56.840824 - OMS Server turned on.
uvicorn.error - INFO - Started server process [87315]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7f852a9b9dc0>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "./main.py", line 1186, in create_order
    if placeOrder(user_name, strategy, instrument_nomenclature, position, quantity, stoploss, target, nomenclature_to_details):
  File "./main.py", line 497, in placeOrder
    ret = addOrderToOrderReference(order_id = order_id, username=username, instrument_nomenclature = instrument_nomenclature, quantity = quantity, position = position, strategy=strategy_name, nomenclature_to_details=nomenclature_to_details)
  File "./main.py", line 655, in addOrderToOrderReference
    return ret
UnboundLocalError: local variable 'ret' referenced before assignment
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [87315]
root - INFO - 2023-06-15 12:46:44.292886 - OMS Server turned on.
uvicorn.error - INFO - Started server process [87385]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7ff36e088d60>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [87385]
root - INFO - 2023-06-15 12:46:47.595575 - OMS Server turned on.
uvicorn.error - INFO - Started server process [87398]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7fa691f78dc0>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "./main.py", line 1188, in create_order
    if placeOrder(user_name, strategy, instrument_nomenclature, position, quantity, stoploss, target, nomenclature_to_details):
  File "./main.py", line 497, in placeOrder
    ret = addOrderToOrderReference(order_id = order_id, username=username, instrument_nomenclature = instrument_nomenclature, quantity = quantity, position = position, strategy=strategy_name, nomenclature_to_details=nomenclature_to_details)
  File "./main.py", line 657, in addOrderToOrderReference
    return ret
UnboundLocalError: local variable 'ret' referenced before assignment
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [87398]
root - INFO - 2023-06-15 12:47:26.320848 - OMS Server turned on.
uvicorn.error - INFO - Started server process [87453]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7f7eca1b7dc0>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "./main.py", line 1188, in create_order
    if placeOrder(user_name, strategy, instrument_nomenclature, position, quantity, stoploss, target, nomenclature_to_details):
  File "./main.py", line 497, in placeOrder
    ret = addOrderToOrderReference(order_id = order_id, username=username, instrument_nomenclature = instrument_nomenclature, quantity = quantity, position = position, strategy=strategy_name, nomenclature_to_details=nomenclature_to_details)
  File "./main.py", line 657, in addOrderToOrderReference
    return ret
UnboundLocalError: local variable 'ret' referenced before assignment
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [87453]
root - INFO - 2023-06-15 12:48:26.615931 - OMS Server turned on.
uvicorn.error - INFO - Started server process [87521]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7fdaa49b8dc0>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "./main.py", line 1191, in create_order
    if placeOrder(user_name, strategy, instrument_nomenclature, position, quantity, stoploss, target, nomenclature_to_details):
  File "./main.py", line 497, in placeOrder
    ret = addOrderToOrderReference(order_id = order_id, username=username, instrument_nomenclature = instrument_nomenclature, quantity = quantity, position = position, strategy=strategy_name, nomenclature_to_details=nomenclature_to_details)
  File "./main.py", line 660, in addOrderToOrderReference
    return ret
UnboundLocalError: local variable 'ret' referenced before assignment
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Finished server process [87521]
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - ERROR - Traceback (most recent call last):
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 624, in lifespan
    await receive()
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/Users/vishaljha/anaconda3/lib/python3.8/asyncio/queues.py", line 163, in get
    await getter
asyncio.exceptions.CancelledError

root - INFO - 2023-06-15 13:33:07.935163 - OMS Server turned on.
uvicorn.error - INFO - Started server process [89671]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7fedba073d60>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
root - INFO - 2023-06-15 13:33:29.322935 - Order placed for fin_user_1 NOVA NIFTY BUY 1 0 0
root - INFO - 2023-06-15 13:33:29.505854 - Order placement successful for users: [{'user_name': 'fin_user_1', 'strategy': 'NOVA', 'instrument_nomenclature': 'NIFTY', 'position': 'BUY', 'target': 0, 'stoploss': 0, 'quantity': 1}]
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [89671]
root - INFO - 2023-06-15 13:35:11.251177 - OMS Server turned on.
uvicorn.error - INFO - Started server process [89811]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7fbaca171b20>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
root - INFO - 2023-06-15 13:35:23.455676 - Order placed for fin_user_1 NOVA NIFTY BUY 1 0 0
root - INFO - 2023-06-15 13:35:23.583165 - Order placement successful for users: [{'user_name': 'fin_user_1', 'strategy': 'NOVA', 'instrument_nomenclature': 'NIFTY', 'position': 'BUY', 'target': 0, 'stoploss': 0, 'quantity': 1}]
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [89811]
root - INFO - 2023-06-15 13:38:10.300190 - OMS Server turned on.
uvicorn.error - INFO - Started server process [89948]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7facdbf6fb20>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [89948]
root - INFO - 2023-06-15 13:40:25.257612 - OMS Server turned on.
uvicorn.error - INFO - Started server process [90152]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7fe9bcf71b20>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
root - INFO - 2023-06-15 13:41:20.652163 - Order placed for fin_user_1 NOVA NIFTY BUY 1 0 0
root - INFO - 2023-06-15 13:41:20.809074 - Order placement successful for users: [{'user_name': 'fin_user_1', 'strategy': 'NOVA', 'instrument_nomenclature': 'NIFTY', 'position': 'BUY', 'target': 0, 'stoploss': 0, 'quantity': 1}]
root - INFO - 2023-06-15 13:42:33.776447 - Order placed for fin_user_1 NOVA NIFTY_SYNTHETIC_INTRADAY_LONG BUY 1 0 0
root - INFO - 2023-06-15 13:42:33.903063 - Order placement successful for users: [{'user_name': 'fin_user_1', 'strategy': 'NOVA', 'instrument_nomenclature': 'NIFTY_SYNTHETIC_INTRADAY_LONG', 'position': 'BUY', 'target': 0, 'stoploss': 0, 'quantity': 1}]
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [90152]
root - INFO - 2023-06-15 13:43:16.975363 - OMS Server turned on.
uvicorn.error - INFO - Started server process [90435]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7fc104078dc0>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [90435]
root - INFO - 2023-06-15 13:44:24.148802 - OMS Server turned on.
uvicorn.error - INFO - Started server process [90582]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7fd19875adc0>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
root - INFO - 2023-06-15 13:44:40.680364 - Order placed for fin_user_1 NOVA NIFTY_SYNTHETIC_INTRADAY_LONG BUY 1 0 0
root - INFO - 2023-06-15 13:44:40.851264 - Order placement successful for users: [{'user_name': 'fin_user_1', 'strategy': 'NOVA', 'instrument_nomenclature': 'NIFTY_SYNTHETIC_INTRADAY_LONG', 'position': 'BUY', 'target': 0, 'stoploss': 0, 'quantity': 1}]
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [90582]
root - INFO - 2023-06-15 13:47:15.367497 - OMS Server turned on.
uvicorn.error - INFO - Started server process [90804]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7fc397073dc0>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
root - INFO - 2023-06-15 13:47:28.133037 - Order placed for fin_user_1 NOVA NIFTY_SYNTHETIC_INTRADAY_LONG BUY 1 0 0
root - INFO - 2023-06-15 13:47:28.325747 - Order placement successful for users: [{'user_name': 'fin_user_1', 'strategy': 'NOVA', 'instrument_nomenclature': 'NIFTY_SYNTHETIC_INTRADAY_LONG', 'position': 'BUY', 'target': 0, 'stoploss': 0, 'quantity': 1}]
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [90804]
root - INFO - 2023-06-15 13:48:43.189595 - OMS Server turned on.
uvicorn.error - INFO - Started server process [90999]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7f8252f73dc0>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
root - INFO - 2023-06-15 13:48:49.172384 - Order placed for fin_user_1 NOVA NIFTY_SYNTHETIC_INTRADAY_LONG BUY 1 0 0
root - INFO - 2023-06-15 13:48:49.341759 - Order placement successful for users: [{'user_name': 'fin_user_1', 'strategy': 'NOVA', 'instrument_nomenclature': 'NIFTY_SYNTHETIC_INTRADAY_LONG', 'position': 'BUY', 'target': 0, 'stoploss': 0, 'quantity': 1}]
root - INFO - 2023-06-15 13:50:00.985762 - Order placed for fin_user_1 NOVA NIFTY_SYNTHETIC_INTRADAY_LONG SELL 1 0 0
root - INFO - 2023-06-15 13:50:01.165520 - Order placement successful for users: [{'user_name': 'fin_user_1', 'strategy': 'NOVA', 'instrument_nomenclature': 'NIFTY_SYNTHETIC_INTRADAY_LONG', 'position': 'SELL', 'target': 0, 'stoploss': 0}]
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [90999]
root - INFO - 2023-06-15 17:45:53.547693 - OMS Server turned on.
uvicorn.error - INFO - Started server process [94518]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7fbe01176dc0>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
root - INFO - 2023-06-15 17:46:13.813692 - Order placed for fin_user_1 NOVA NIFTY OPEN SHORT -1 0 0
root - INFO - 2023-06-15 17:46:13.975480 - Order placement successful for users: [{'user_name': 'fin_user_1', 'strategy': 'NOVA', 'instrument_nomenclature': 'NIFTY', 'position': 'OPEN SHORT', 'target': 0, 'stoploss': 0, 'quantity': 1}]
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Finished server process [94518]
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - ERROR - Traceback (most recent call last):
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 624, in lifespan
    await receive()
  File "/Users/vishaljha/anaconda3/lib/python3.8/site-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/Users/vishaljha/anaconda3/lib/python3.8/asyncio/queues.py", line 163, in get
    await getter
asyncio.exceptions.CancelledError

root - INFO - 2023-06-15 17:49:03.789450 - OMS Server turned on.
uvicorn.error - INFO - Started server process [94943]
uvicorn.error - INFO - Waiting for application startup.
tortoise - INFO - Tortoise-ORM started, {'default': <tortoise.backends.sqlite.client.SqliteClient object at 0x7fdf6af77dc0>}, {'models': {'OptionSpread': <class 'models.OptionSpread'>, 'User': <class 'models.User'>, 'User_Finvant': <class 'models.User_Finvant'>}}
tortoise - INFO - Tortoise-ORM generating schema
uvicorn.error - INFO - Application startup complete.
root - INFO - 2023-06-15 17:49:41.217227 - Order placed for fin_user_1 NOVA NIFTY OPEN SHORT -1 0 0
root - INFO - 2023-06-15 17:49:41.432728 - Order placement successful for users: [{'user_name': 'fin_user_1', 'strategy': 'NOVA', 'instrument_nomenclature': 'NIFTY', 'position': 'OPEN SHORT', 'target': 0, 'stoploss': 0, 'quantity': 1}]
root - INFO - 2023-06-15 17:50:09.323200 - Order placed for fin_user_1 NOVA NIFTY CLOSE SHORT -1 0 0
root - INFO - 2023-06-15 17:50:09.483213 - Order placement successful for users: [{'user_name': 'fin_user_1', 'strategy': 'NOVA', 'instrument_nomenclature': 'NIFTY', 'position': 'CLOSE SHORT', 'target': 0, 'stoploss': 0}]
uvicorn.error - INFO - Shutting down
uvicorn.error - INFO - Waiting for application shutdown.
tortoise - INFO - Tortoise-ORM shutdown
tortoise - INFO - Tortoise-ORM shutdown
uvicorn.error - INFO - Application shutdown complete.
uvicorn.error - INFO - Finished server process [94943]
